apiVersion: batch/v1
kind: CronJob
metadata:
  name: pregod-1-1-beat
  namespace: pregod
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 21600
      template:
        spec:
          containers:
            - image: $IMAGE_TAG_RELEASE
              imagePullPolicy: Always
              name: pregod-1-1
              envFrom:
                - secretRef:
                    name: pregod-1-1
              command:
                - beat
              resources:
                requests:
                  memory: "50Mi"
                  cpu: "50m"
                limits:
                  memory: "500Mi"
                  cpu: "500m"
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: "10 * * * *"
  successfulJobsHistoryLimit: 3
  suspend: false
