apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pregod2-hub
  namespace: pregod
spec:
  maxReplicas: 5
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pregod2-hub
  targetCPUUtilizationPercentage: 70
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pregod2-indexer
  namespace: pregod
spec:
  maxReplicas: 5
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pregod2-indexer
  targetCPUUtilizationPercentage: 70
