apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pregod-1-1-hub
  namespace: pregod
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pregod-1-1-hub
  targetCPUUtilizationPercentage: 70
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pregod-1-1-indexer
  namespace: pregod
spec:
  maxReplicas: 12
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pregod-1-1-indexer
  targetCPUUtilizationPercentage: 70
