apiVersion: v1
kind: ServiceAccount
metadata:
  name: restart-sa
  namespace: pregod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: restart-role
  namespace: pregod
rules:
- apiGroups: ["apps", "extensions"]
  resources: ["deployments"]
  resourceNames: ["pregod-1-1-indexer", "pregod-1-1-indexer-io"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: restart-rolebinding
  namespace: pregod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: restart-role
subjects:
- kind: ServiceAccount
  name: restart-sa
  namespace: pregod
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: pregod-1-1-restart-cronjob
  namespace: pregod
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: restart-sa
          containers:
          - name: kubectl
            image: bitnami/kubectl
            command:
            - kubectl
            - -n
            - pregod
            - rollout
            - restart
            - deployment/pregod-1-1-indexer
            - deployment/pregod-1-1-indexer-io
          restartPolicy: OnFailure

