apiVersion: v1
kind: Service
metadata:
  name: pregod2-hub-api
  namespace: pregod
spec:
  type: ClusterIP
  selector:
    app: pregod2-hub
    tier: api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
