mode: development

http:
  host: 0.0.0.0
  port: 80

postgres:
  host: 127.0.0.1
  port: 5432
  user: postgres
  password: password
  database: pregod11
  socialdburl: ""

ethereumetl:
  host: 127.0.0.1
  port: 5433
  user: postgres
  password: password
  database: etl

rabbitmq:
  tls: false
  host: 127.0.0.1
  port: 5672
  user: guest
  password: guest

opentelemetry:
  enabled: false
  host: 127.0.0.1
  port: 14268
  path: /api/traces

kurora:
  endpoint: ''

redis:
  tls: false
  addr: 127.0.0.1:6379
  db: 0
  password: ''

rpc:
  general:
    ethereum:
      http: ''
      websocket: ''
    polygon:
      http: ''
      websocket: ''
    bsc:
      http: ''
      websocket: ''
    xdai:
      http: ''
      websocket: ''
    crossbell:
      http: ''
      websocket: ''
    arbitrum:
      http: ''
      websocket: ''
    optimism:
      http: ''
      websocket: ''
    avalanche:
      http: ''
    fantom:
      http: ''
      websocket: ''
    celo:
      http: ''
      websocket: ''
  alchemy:
    ethereum: ''
    polygon: ''
  pregod_etl:
    polygon:
      http: ''
  ipfs:
    io: ''
    internal: ''
