name: lint & test
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
      - develop
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          which bash
          bash --version
          bash apply.sh deploy/prod/*
