name: lint & test
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
      - develop
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
  tests:
    name: "UnitTest"
    runs-on: ubuntu-latest
    services:
      pgsql:
        image: "postgres:13.4"
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
          POSTGRES_DB: pregod2
        ports:
          - "5432:5432"
      rabbitmq:
        image: rabbitmq:3-management
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - "5672:5672"
          - "15672:15672"
    steps:
      - name: Check out code into Go module directory
        uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Go mod package cache
        uses: actions/cache@v3
        with:
          path: $GOPATH/pkg/mod
          key: ${{ runner.os }}-${{ hashFiles('**/go.sum') }}
      - name: Run tests
        env:
          CONFIG_ENV_POSTGRES_HOST: pgsql
          CONFIG_ENV_RABBITMQ_HOST: rabbitmq
        run: |
          go install github.com/wadey/gocovmerge@latest
          make test # should be `make coverage_fail`
